# Generated by Django 2.2.6 on 2019-10-09 11:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('host', models.CharField(max_length=60)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, default='n/a', editable=False, max_length=10)),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Password')),
                ('domain', models.CharField(blank=True, max_length=50, null=True, verbose_name='Domain')),
                ('passthrough_credentials', models.BooleanField(default=False, verbose_name='Passthrough app login credentials')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='backend.Folder')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_backend.connection_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ConnectionRdp',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Connection')),
                ('ignore_cert', models.BooleanField(default=False)),
                ('security', models.CharField(choices=[('rdp', 'RDP'), ('nla', 'NLA'), ('tls', 'TLS'), ('any', 'ANY')], default='any', max_length=10)),
                ('disable_auth', models.BooleanField(default=False)),
                ('console', models.BooleanField(default=False)),
                ('initial_program', models.CharField(blank=True, max_length=255, null=True)),
                ('server_layout', models.CharField(choices=[('en-us-qwerty', 'English (US) keyboard'), ('failsafe', 'Failsafe')], default='failsafe', max_length=12)),
                ('color_depth', models.CharField(choices=[('8', '8 bits'), ('16', '16 bits'), ('24', '24 bits')], default='8', max_length=2)),
                ('resize_method', models.CharField(choices=[('reconnect', 'Reconnect'), ('display-update', 'Display Update')], default='reconnect', max_length=20)),
            ],
            options={
                'verbose_name': 'RDP Connection',
                'verbose_name_plural': 'RDP Connections',
            },
            bases=('backend.connection',),
        ),
        migrations.CreateModel(
            name='ConnectionSsh',
            fields=[
                ('connection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Connection')),
                ('host_key', models.TextField(blank=True, verbose_name='Host Key')),
                ('server_alive_interval', models.IntegerField(default=0, verbose_name='Keepalive interval')),
                ('private_key', models.TextField(blank=True, null=True, verbose_name='Private Key')),
                ('passphrase', models.CharField(blank=True, max_length=100, null=True)),
                ('font_size', models.IntegerField(blank=True, default=8)),
                ('command', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'SSH Connection',
                'verbose_name_plural': 'SSH Connections',
            },
            bases=('backend.connection',),
        ),
    ]
