# Generated by Django 2.2.6 on 2019-10-09 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_connection_connectionrdp_connectionssh'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuacdServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='guacd server', max_length=64, unique=True)),
                ('hostname', models.CharField(default='localhost', max_length=64)),
                ('port', models.PositiveIntegerField(default=4822, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
            ],
            options={
                'verbose_name': 'Guacd Server',
                'verbose_name_plural': 'Guacd Servers',
            },
        ),
    ]
