# Generated by Django 2.2.6 on 2019-10-09 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_guacdserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Credentials',
                'verbose_name_plural': 'Credentials',
            },
        ),
        migrations.CreateModel(
            name='NamedCredentials',
            fields=[
                ('credentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Credentials')),
                ('default_domain', models.CharField(blank=True, max_length=50, verbose_name='Default domain')),
            ],
            options={
                'verbose_name': 'Named Credentials',
                'verbose_name_plural': 'Named Credentials',
            },
            bases=('backend.credentials',),
        ),
        migrations.CreateModel(
            name='StaticCredentials',
            fields=[
                ('credentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Credentials')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='Password')),
                ('domain', models.CharField(blank=True, max_length=50, verbose_name='Domain')),
                ('private_key', models.TextField(blank=True, verbose_name='Private Key')),
                ('passphrase', models.CharField(blank=True, max_length=32, verbose_name='Passphrase')),
            ],
            options={
                'verbose_name': 'Static credentials',
                'verbose_name_plural': 'Static credentials',
            },
            bases=('backend.credentials', models.Model),
        ),
        migrations.CreateModel(
            name='PersonalNamedCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='Password')),
                ('domain', models.CharField(blank=True, max_length=50, verbose_name='Domain')),
                ('private_key', models.TextField(blank=True, verbose_name='Private Key')),
                ('passphrase', models.CharField(blank=True, max_length=32, verbose_name='Passphrase')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='backend.NamedCredentials')),
            ],
            options={
                'verbose_name': 'Personal Named Credentials',
                'verbose_name_plural': 'Personal Named Credentials',
            },
        ),
    ]
