# Generated by Django 2.2.6 on 2019-10-14 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_appsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='guacdserver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='backend.GuacdServer'),
        ),
    ]
