# Generated by Django 2.2.6 on 2019-10-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_connection_guacdserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Credentials', verbose_name='Credentials'),
        ),
    ]
