# Generated by Django 2.2.6 on 2019-10-17 20:42

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_connection_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='personalnamedcredentials',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='staticcredentials',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Password'),
        ),
    ]
