# Generated by Django 2.2.6 on 2019-10-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_encrypt_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
