# Generated by Django 2.2.6 on 2019-10-22 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0011_connectionvnc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ticketid', models.UUIDField(null=True)),
                ('action', models.CharField(max_length=20)),
                ('shared', models.BooleanField(default=False)),
                ('sessionid', models.UUIDField(blank=True, null=True)),
                ('connection_name', models.CharField(max_length=60)),
                ('connection_host', models.CharField(max_length=60)),
                ('connection_port', models.IntegerField(default=0)),
                ('connection_protocol', models.CharField(max_length=10)),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author_username', models.CharField(blank=True, max_length=60, null=True)),
                ('author_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guacdserver_hostname', models.CharField(default='localhost', max_length=64)),
                ('guacdserver_port', models.PositiveIntegerField()),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_in_ticketlogs', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Connection')),
                ('guacdserver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.GuacdServer')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_in_ticketlogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
