# Generated by Django 2.2.6 on 2019-10-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_ticketlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='ignore_rdp_cert_by_default',
            field=models.BooleanField(default=True),
        ),
    ]
