# Generated by Django 2.2.6 on 2019-10-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_appsettings_ignore_rdp_cert_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlog',
            name='ip',
            field=models.GenericIPAddressField(null=True, unpack_ipv4=True),
        ),
    ]
