# Generated by Django 2.2.6 on 2019-10-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_ticketlog_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='control',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='control',
            field=models.BooleanField(default=True, verbose_name='Control'),
        ),
    ]
