# Generated by Django 2.2.6 on 2019-11-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_ticket_ticketlog_add_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrdp',
            name='color_depth',
            field=models.CharField(choices=[('8', '8 bits'), ('16', '16 bits'), ('24', '24 bits')], default='16', max_length=2),
        ),
        migrations.AlterField(
            model_name='connectionrdp',
            name='server_layout',
            field=models.CharField(choices=[('en-us-qwerty', 'English (US) keyboard'), ('en-gb-qwerty', 'English (UK) keyboard'), ('de-de-qwertz', 'German keyboard (qwertz)'), ('fr-fr-azerty', 'French keyboard (azerty)'), ('fr-ch-qwertz', 'Swiss French keyboard (qwertz)'), ('it-it-qwerty', 'Italian keyboard'), ('ja-jp-qwerty', 'Japanese keyboard'), ('pt-br-qwerty', 'Portuguese Brazilian keyboard'), ('es-es-qwerty', 'Spanish keyboard'), ('sv-se-qwerty', 'Swedish keyboard'), ('tr-tr-qwerty', 'Turkish-Q keyboard'), ('failsafe', 'Failsafe')], default='en-us-qwerty', max_length=12),
        ),
    ]
