# Generated by Django 2.2.6 on 2019-11-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_connectionrdp_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionssh',
            name='terminal_type',
            field=models.CharField(blank=True, choices=[('ansi', 'ansi'), ('linux', 'linux'), ('vt100', 'vt100'), ('vt220', 'vt220'), ('xterm', 'xterm'), ('xterm-256colors', 'xterm-256colors')], max_length=32, null=True),
        ),
    ]
