ARG BUILDFROM=node:12.2.0-alpine
ARG FROM=nginx:1.17.4-alpine

###########
# BUILDER #
###########

FROM ${BUILDFROM} as builder
ADD frontend/package.json /frontend/
ADD frontend/package-lock.json /frontend/
WORKDIR /frontend
RUN npm install
ADD frontend /frontend
RUN npm run build

#########
# FINAL #
#########

FROM ${FROM}

COPY --chown=nginx:nginx --from=builder /frontend/build /frontend
COPY --chown=nginx:nginx docker/nginx.conf /etc/nginx/nginx.conf

RUN rm /etc/nginx/conf.d/default.conf && \
    apk add --no-cache bash
