FROM python:3.7-alpine3.10

RUN apk add --no-cache \
      bash \
      build-base \
      ca-certificates \
      git \
      libffi-dev \
      openldap-dev \
      wget \
      nginx

COPY guacozy_server/requirements* /tmp/
WORKDIR /tmp/
RUN pip install -r requirements-ldap.txt

COPY guacozy_server /opt/guacozy_server


WORKDIR /opt/guacozy_server/
COPY docker/docker-entrypoint.sh /opt/guacozy_server/docker-entrypoint.sh
ENTRYPOINT [ "/opt/guacozy_server/docker-entrypoint.sh" ]
CMD ["daphne", "-b", "0.0.0.0","-p","8001","guacozy_server.asgi:application"]
EXPOSE 8001