#!/bin/bash
# https://windsock.io/automated-docker-image-builds-with-multiple-tags/

set -e

# Tag and push image for each additional tag
if [ $DOCKER_TAG != 'develop']; then
    docker tag $IMAGE_NAME $DOCKER_REPO:latest
    docker push $DOCKER_REPO:latest
fi